- hosts: all
  remote_user: djskullz8
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Instalar pip2, pip3, Git y PostgresSQL
      become: true
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - python-pip
        - python3-pip
        - git
        - postgresql
        - postgresql-contrib

    - name: Clone a private repository into IV-18-19-Proyecto
      git:
        repo: https://github.com/Thejokeri/IV-18-19-Proyecto.git
        version: master
        dest: IV-18-19-Proyecto/
      become: no

    - name: Sincronizando la carpeta local
      synchronize:
        src: /Users/thejoker/Documents/Facultad/1ºSemestre/IV/IV-18-19-Proyecto/importante
        dest: .

    - name: Instalar requirements.txt
      become: true
      command: pip install -r ./IV-18-19-Proyecto/requirements.txt

    - name: Crear usuario postgres "{{ lookup('env','USER') }}"
      become: yes
      become_user: postgres
      postgresql_user:
        name: "{{ lookup('env','USER') }}"
        password: "{{ lookup('env','PASS') }}"

    - name: Crear la base de datos PDFdb
      become: yes
      become_user: postgres 
      postgresql_db:
        name: pdfdb
        owner: "{{ lookup('env','USER') }}"